

export enum BlogUsersReducerEnum {
    SET_BLOG_USERS='SET_BLOG_USERS',
    SET_BLOG_POSTS='SET_BLOG_POSTS',
    SET_SELECTED_BLOG_USER_ID='SET_SELECTED_BLOG_USER_ID',
    SET_COMMENTS_MODAL_STATUS='SET_COMMENTS_MODAL_STATUS',
    SET_IS_LOADING_STATUS='SET_IS_LOADING_STATUS',
    SET_SEARCH_STRING='SET_SEARCH_STRING',
    SET_COMMENTS='SET_COMMENTS',
    SET_ACTIVE_POST='SET_ACTIVE_POST'
}