

export enum FilmReducerEnum {
    SET_FILMS='SET_FILMS',
    GET_FILMS_SAGA='GET_FILMS_SAGA',
    SET_FAVORITE_FILMS='SET_FAVORITE_FILMS',
    SET_SELECTED_FILM='SET_SELECTED_FILM',
    SET_COMMENTS='SET_COMMENTS',
}